# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: items.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "items.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bitems.proto\x12\x05items"\x1e\n\x0bItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05",\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05"\xbb\x01\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0b\n\x03sku\x18\x05 \x01(\t\x12\x12\n\ncodigo_sku\x18\x06 \x01(\t\x12\r\n\x05stock\x18\x07 \x01(\x05\x12\x11\n\teliminado\x18\x08 \x01(\x08\x12\x14\n\x0c\x65liminado_en\x18\t \x01(\t\x12\x14\n\x0c\x63\x61tegoria_id\x18\n \x01(\x05\x32y\n\x0bItemService\x12\x32\n\x07GetItem\x12\x12.items.ItemRequest\x1a\x13.items.ItemResponse\x12\x36\n\tListItems\x12\x12.items.ListRequest\x1a\x13.items.ItemResponse0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "items_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ITEMREQUEST"]._serialized_start = 22
    _globals["_ITEMREQUEST"]._serialized_end = 52
    _globals["_LISTREQUEST"]._serialized_start = 54
    _globals["_LISTREQUEST"]._serialized_end = 98
    _globals["_ITEMRESPONSE"]._serialized_start = 101
    _globals["_ITEMRESPONSE"]._serialized_end = 288
    _globals["_ITEMSERVICE"]._serialized_start = 290
    _globals["_ITEMSERVICE"]._serialized_end = 411
# @@protoc_insertion_point(module_scope)
