"""create movimientos stock table

Revision ID: 07ba0f6e9447
Revises: 0f6a802938c3
Create Date: 2026-03-06 12:24:29.723008

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "07ba0f6e9447"
down_revision: Union[str, Sequence[str], None] = "0f6a802938c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
