"""create movimientos stock table

Revision ID: 0f6a802938c3
Revises: 5d46e415f28a
Create Date: 2026-03-06 12:12:22.368429

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f6a802938c3"
down_revision: Union[str, Sequence[str], None] = "5d46e415f28a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movimientos_stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_origen_id", sa.Integer(), nullable=False),
        sa.Column("item_destino_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("usuario", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_destino_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_origen_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movimientos_stock_created_at"), "movimientos_stock", ["created_at"], unique=False)
    op.create_index(op.f("ix_movimientos_stock_id"), "movimientos_stock", ["id"], unique=False)
    op.create_index(
        op.f("ix_movimientos_stock_item_destino_id"), "movimientos_stock", ["item_destino_id"], unique=False
    )
    op.create_index(op.f("ix_movimientos_stock_item_origen_id"), "movimientos_stock", ["item_origen_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movimientos_stock_item_origen_id"), table_name="movimientos_stock")
    op.drop_index(op.f("ix_movimientos_stock_item_destino_id"), table_name="movimientos_stock")
    op.drop_index(op.f("ix_movimientos_stock_id"), table_name="movimientos_stock")
    op.drop_index(op.f("ix_movimientos_stock_created_at"), table_name="movimientos_stock")
    op.drop_table("movimientos_stock")
    # ### end Alembic commands ###
