"""add imagen_key

Revision ID: 208133f867a9
Revises: 7193592cb577
Create Date: 2026-03-24 13:24:45.721472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208133f867a9'
down_revision: Union[str, Sequence[str], None] = '7193592cb577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_cors_id'), table_name='configuracion_cors')
    op.drop_index(op.f('ix_configuracion_cors_origin'), table_name='configuracion_cors')
    op.drop_table('configuracion_cors')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_item_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_saga_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_oauth_refresh_tokens_token'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_user_email'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_index(op.f('ix_consentimientos_privacidad_id'), table_name='consentimientos_privacidad')
    op.drop_index(op.f('ix_consentimientos_privacidad_usuario_id'), table_name='consentimientos_privacidad')
    op.drop_table('consentimientos_privacidad')
    op.drop_index(op.f('ix_items_lectura_categoria_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_codigo_sku'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_eliminado'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_name'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_sku'), table_name='items_lectura')
    op.drop_table('items_lectura')
    op.drop_index(op.f('ix_saga_log_id'), table_name='saga_log')
    op.drop_index(op.f('ix_saga_log_saga_id'), table_name='saga_log')
    op.drop_index(op.f('ix_saga_log_status'), table_name='saga_log')
    op.drop_index(op.f('ix_saga_log_step'), table_name='saga_log')
    op.drop_table('saga_log')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_table('security_events')
    op.add_column('items', sa.Column('imagen_key', sa.String(length=255), nullable=True, comment='Clave del archivo en S3 (NO URL pública)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'imagen_key')
    op.create_table('security_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detalles', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accion_tomada', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('security_events_pkey'))
    )
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_ip'), 'security_events', ['ip'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('saga_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('saga_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('saga_log_pkey')),
    sa.UniqueConstraint('saga_id', 'step', name=op.f('uq_saga_log_saga_id_step'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_saga_log_step'), 'saga_log', ['step'], unique=False)
    op.create_index(op.f('ix_saga_log_status'), 'saga_log', ['status'], unique=False)
    op.create_index(op.f('ix_saga_log_saga_id'), 'saga_log', ['saga_id'], unique=False)
    op.create_index(op.f('ix_saga_log_id'), 'saga_log', ['id'], unique=False)
    op.create_table('items_lectura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('codigo_sku', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('disponible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('precio_con_impuesto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('eliminado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('eliminado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_lectura_pkey'))
    )
    op.create_index(op.f('ix_items_lectura_sku'), 'items_lectura', ['sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_name'), 'items_lectura', ['name'], unique=False)
    op.create_index(op.f('ix_items_lectura_id'), 'items_lectura', ['id'], unique=False)
    op.create_index(op.f('ix_items_lectura_eliminado'), 'items_lectura', ['eliminado'], unique=False)
    op.create_index(op.f('ix_items_lectura_codigo_sku'), 'items_lectura', ['codigo_sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_categoria_id'), 'items_lectura', ['categoria_id'], unique=False)
    op.create_table('consentimientos_privacidad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_aviso', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Versión del aviso de privacidad aceptado'),
    sa.Column('ip_cliente', sa.VARCHAR(length=45), autoincrement=False, nullable=False, comment='IP del cliente al aceptar el aviso'),
    sa.Column('fecha_aceptacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('consentimientos_privacidad_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consentimientos_privacidad_pkey'))
    )
    op.create_index(op.f('ix_consentimientos_privacidad_usuario_id'), 'consentimientos_privacidad', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_consentimientos_privacidad_id'), 'consentimientos_privacidad', ['id'], unique=False)
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_user_email'), 'oauth_refresh_tokens', ['user_email'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_token'), 'oauth_refresh_tokens', ['token'], unique=True)
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('saga_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('email_cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pedidos_pkey'))
    )
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_pedidos_saga_id'), 'pedidos', ['saga_id'], unique=True)
    op.create_index(op.f('ix_pedidos_item_id'), 'pedidos', ['item_id'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_table('configuracion_cors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('configuracion_cors_pkey'))
    )
    op.create_index(op.f('ix_configuracion_cors_origin'), 'configuracion_cors', ['origin'], unique=True)
    op.create_index(op.f('ix_configuracion_cors_id'), 'configuracion_cors', ['id'], unique=False)
    # ### end Alembic commands ###
