"""add proveedor to items

Revision ID: 5d46e415f28a
Revises: beffe1070ac5
Create Date: 2026-03-06 11:59:48.576707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d46e415f28a"
down_revision: Union[str, Sequence[str], None] = "beffe1070ac5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("proveedor", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "proveedor")
    # ### end Alembic commands ###
