"""add indexes to items table

Revision ID: 6021b7c28b7c
Revises: 07ba0f6e9447
Create Date: 2026-03-06 13:05:35.006279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6021b7c28b7c'
down_revision: Union[str, Sequence[str], None] = '07ba0f6e9447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_items_name_eliminado', 'items', ['name', 'eliminado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_name_eliminado', table_name='items')
    # ### end Alembic commands ###
