"""oauth2 tables

Revision ID: 6248ee81e571
Revises: 0b42d0f2d8ef
Create Date: 2026-03-13 19:03:43.825482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6248ee81e571'
down_revision: Union[str, Sequence[str], None] = '0b42d0f2d8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_lectura_categoria_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_codigo_sku'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_eliminado'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_name'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_sku'), table_name='items_lectura')
    op.drop_table('items_lectura')
    op.drop_index(op.f('ix_configuracion_cors_id'), table_name='configuracion_cors')
    op.drop_index(op.f('ix_configuracion_cors_origin'), table_name='configuracion_cors')
    op.drop_table('configuracion_cors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_cors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_cors_origin'), 'configuracion_cors', ['origin'], unique=1)
    op.create_index(op.f('ix_configuracion_cors_id'), 'configuracion_cors', ['id'], unique=False)
    op.create_table('items_lectura',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), nullable=True),
    sa.Column('codigo_sku', sa.VARCHAR(length=20), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), nullable=True),
    sa.Column('categoria_nombre', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disponible', sa.BOOLEAN(), nullable=False),
    sa.Column('precio_con_impuesto', sa.FLOAT(), nullable=False),
    sa.Column('eliminado', sa.BOOLEAN(), nullable=False),
    sa.Column('eliminado_en', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_lectura_sku'), 'items_lectura', ['sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_name'), 'items_lectura', ['name'], unique=False)
    op.create_index(op.f('ix_items_lectura_id'), 'items_lectura', ['id'], unique=False)
    op.create_index(op.f('ix_items_lectura_eliminado'), 'items_lectura', ['eliminado'], unique=False)
    op.create_index(op.f('ix_items_lectura_codigo_sku'), 'items_lectura', ['codigo_sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_categoria_id'), 'items_lectura', ['categoria_id'], unique=False)
    # ### end Alembic commands ###
