"""diff_check

Revision ID: 7193592cb577
Revises: efe11bb5547a
Create Date: 2026-03-17 16:09:09.444023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7193592cb577'
down_revision: Union[str, Sequence[str], None] = 'efe11bb5547a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('umbral', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_stock_id'), 'reportes_stock', ['id'], unique=False)
    op.drop_index(op.f('ix_consentimientos_datos_personales_usuario_id'), table_name='consentimientos_datos_personales')
    op.drop_table('consentimientos_datos_personales')
    op.drop_index(op.f('ix_security_events_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('configuracion_cors')
    op.drop_index(op.f('ix_oauth_refresh_tokens_token'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_user_email'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_index(op.f('ix_solicitudes_arco_estatus'), table_name='solicitudes_arco')
    op.drop_index(op.f('ix_solicitudes_arco_usuario_id'), table_name='solicitudes_arco')
    op.drop_table('solicitudes_arco')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.alter_column('auditoria_items', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_auditoria_items_id'), 'auditoria_items', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_items_usuario_id'), 'auditoria_items', ['usuario_id'], unique=False)
    op.drop_constraint(None, 'auditoria_items', type_='foreignkey')
    op.add_column('usuarios', sa.Column('nombre', sa.String(length=255), nullable=True, comment='Nombre del usuario'))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('usuarios', sa.Column('ultimo_acceso_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_usuarios_anonimizado'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_rfc'), 'usuarios', ['rfc'], unique=False)
    op.drop_column('usuarios', 'solicitud_arco_estatus')
    op.drop_column('usuarios', 'anonimizado')
    op.drop_column('usuarios', 'solicitud_arco_tipo')
    op.drop_column('usuarios', 'consentimiento_datos')
    op.drop_column('usuarios', 'motivo_anonimizacion')
    op.drop_column('usuarios', 'origen_consentimiento')
    op.drop_column('usuarios', 'fecha_anonimizacion')
    op.drop_column('usuarios', 'solicitud_arco_fecha')
    op.drop_column('usuarios', 'fecha_consentimiento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DATETIME(), nullable=True))
    op.add_column('usuarios', sa.Column('solicitud_arco_fecha', sa.DATETIME(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_anonimizacion', sa.DATETIME(), nullable=True))
    op.add_column('usuarios', sa.Column('origen_consentimiento', sa.VARCHAR(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('motivo_anonimizacion', sa.VARCHAR(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('consentimiento_datos', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False))
    op.add_column('usuarios', sa.Column('solicitud_arco_tipo', sa.VARCHAR(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('anonimizado', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False))
    op.add_column('usuarios', sa.Column('solicitud_arco_estatus', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_usuarios_rfc'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_anonimizado'), 'usuarios', ['anonimizado'], unique=False)
    op.drop_column('usuarios', 'ultimo_acceso_at')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'nombre')
    op.create_foreign_key(None, 'auditoria_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auditoria_items_usuario_id'), table_name='auditoria_items')
    op.drop_index(op.f('ix_auditoria_items_id'), table_name='auditoria_items')
    op.alter_column('auditoria_items', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_table('oauth_clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('client_secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('redirect_uris', sqlite.JSON(), nullable=False),
    sa.Column('scopes', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=1)
    op.create_table('solicitudes_arco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estatus', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('detalle', sa.TEXT(), nullable=True),
    sa.Column('fecha_solicitud', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_resolucion', sa.DATETIME(), nullable=True),
    sa.Column('respuesta', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_arco_usuario_id'), 'solicitudes_arco', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_arco_estatus'), 'solicitudes_arco', ['estatus'], unique=False)
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_user_email'), 'oauth_refresh_tokens', ['user_email'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_token'), 'oauth_refresh_tokens', ['token'], unique=1)
    op.create_table('configuracion_cors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detalles', sa.TEXT(), nullable=False),
    sa.Column('accion_tomada', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pais', sa.VARCHAR(length=10), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_ip'), 'security_events', ['ip'], unique=False)
    op.create_table('consentimientos_datos_personales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_consentimiento', sa.VARCHAR(length=100), nullable=False),
    sa.Column('otorgado', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('fecha_otorgado', sa.DATETIME(), nullable=True),
    sa.Column('version_aviso_privacidad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('origen', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimientos_datos_personales_usuario_id'), 'consentimientos_datos_personales', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_reportes_stock_id'), table_name='reportes_stock')
    op.drop_table('reportes_stock')
    # ### end Alembic commands ###
