"""integracion legacy

Revision ID: 79ce4fda9652
Revises: 208133f867a9
Create Date: 2026-03-26 13:26:23.716981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ce4fda9652'
down_revision: Union[str, Sequence[str], None] = '208133f867a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_lectura_categoria_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_codigo_sku'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_eliminado'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_id'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_name'), table_name='items_lectura')
    op.drop_index(op.f('ix_items_lectura_sku'), table_name='items_lectura')
    op.drop_table('items_lectura')
    op.drop_index(op.f('ix_configuracion_cors_id'), table_name='configuracion_cors')
    op.drop_index(op.f('ix_configuracion_cors_origin'), table_name='configuracion_cors')
    op.drop_table('configuracion_cors')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_idempotency_key'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_pedido_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_stripe_payment_intent_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_consentimientos_privacidad_id'), table_name='consentimientos_privacidad')
    op.drop_index(op.f('ix_consentimientos_privacidad_usuario_id'), table_name='consentimientos_privacidad')
    op.drop_table('consentimientos_privacidad')
    op.drop_index(op.f('ix_notificaciones_enviadas_id'), table_name='notificaciones_enviadas')
    op.drop_table('notificaciones_enviadas')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_item_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_saga_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_oauth_refresh_tokens_token'), table_name='oauth_refresh_tokens')
    op.drop_index(op.f('ix_oauth_refresh_tokens_user_email'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_user_email'), 'oauth_refresh_tokens', ['user_email'], unique=False)
    op.create_index(op.f('ix_oauth_refresh_tokens_token'), 'oauth_refresh_tokens', ['token'], unique=1)
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('saga_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('monto_total', sa.FLOAT(), nullable=False),
    sa.Column('email_cliente', sa.VARCHAR(length=255), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_pedidos_saga_id'), 'pedidos', ['saga_id'], unique=1)
    op.create_index(op.f('ix_pedidos_item_id'), 'pedidos', ['item_id'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_table('notificaciones_enviadas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('destinatario', sa.VARCHAR(), nullable=False),
    sa.Column('canal', sa.VARCHAR(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(), nullable=False),
    sa.Column('estado', sa.VARCHAR(), nullable=False),
    sa.Column('intentos', sa.INTEGER(), nullable=True),
    sa.Column('error_mensaje', sa.TEXT(), nullable=True),
    sa.Column('enviado_en', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_enviadas_id'), 'notificaciones_enviadas', ['id'], unique=False)
    op.create_table('consentimientos_privacidad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('version_aviso', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ip_cliente', sa.VARCHAR(length=45), nullable=False),
    sa.Column('fecha_aceptacion', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimientos_privacidad_usuario_id'), 'consentimientos_privacidad', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_consentimientos_privacidad_id'), 'consentimientos_privacidad', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('monto', sa.FLOAT(), nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_stripe_payment_intent_id'), 'pagos', ['stripe_payment_intent_id'], unique=1)
    op.create_index(op.f('ix_pagos_pedido_id'), 'pagos', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pagos_idempotency_key'), 'pagos', ['idempotency_key'], unique=1)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detalles', sa.TEXT(), nullable=False),
    sa.Column('accion_tomada', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pais', sa.VARCHAR(length=10), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_ip'), 'security_events', ['ip'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('configuracion_cors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_cors_origin'), 'configuracion_cors', ['origin'], unique=1)
    op.create_index(op.f('ix_configuracion_cors_id'), 'configuracion_cors', ['id'], unique=False)
    op.create_table('items_lectura',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), nullable=True),
    sa.Column('codigo_sku', sa.VARCHAR(length=20), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('categoria_id', sa.INTEGER(), nullable=True),
    sa.Column('categoria_nombre', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disponible', sa.BOOLEAN(), nullable=False),
    sa.Column('precio_con_impuesto', sa.FLOAT(), nullable=False),
    sa.Column('eliminado', sa.BOOLEAN(), nullable=False),
    sa.Column('eliminado_en', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_lectura_sku'), 'items_lectura', ['sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_name'), 'items_lectura', ['name'], unique=False)
    op.create_index(op.f('ix_items_lectura_id'), 'items_lectura', ['id'], unique=False)
    op.create_index(op.f('ix_items_lectura_eliminado'), 'items_lectura', ['eliminado'], unique=False)
    op.create_index(op.f('ix_items_lectura_codigo_sku'), 'items_lectura', ['codigo_sku'], unique=False)
    op.create_index(op.f('ix_items_lectura_categoria_id'), 'items_lectura', ['categoria_id'], unique=False)
    # ### end Alembic commands ###
