"""add auditoria_items

Revision ID: c6ea1aa925a5
Revises: e0c73d37628a
Create Date: 2026-03-08 12:48:20.381695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ea1aa925a5'
down_revision: Union[str, Sequence[str], None] = 'e0c73d37628a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_cliente', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_items_accion'), 'auditoria_items', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_items_id'), 'auditoria_items', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_items_item_id'), 'auditoria_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_auditoria_items_timestamp'), 'auditoria_items', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auditoria_items_usuario_id'), 'auditoria_items', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_configuracion_cors_id'), table_name='configuracion_cors')
    op.drop_index(op.f('ix_configuracion_cors_origin'), table_name='configuracion_cors')
    op.drop_table('configuracion_cors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_cors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_cors_origin'), 'configuracion_cors', ['origin'], unique=1)
    op.create_index(op.f('ix_configuracion_cors_id'), 'configuracion_cors', ['id'], unique=False)
    op.drop_index(op.f('ix_auditoria_items_usuario_id'), table_name='auditoria_items')
    op.drop_index(op.f('ix_auditoria_items_timestamp'), table_name='auditoria_items')
    op.drop_index(op.f('ix_auditoria_items_item_id'), table_name='auditoria_items')
    op.drop_index(op.f('ix_auditoria_items_id'), table_name='auditoria_items')
    op.drop_index(op.f('ix_auditoria_items_accion'), table_name='auditoria_items')
    op.drop_table('auditoria_items')
    # ### end Alembic commands ###
