input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {

  if ![trace_id] {
    mutate {
      add_field => { "trace_id" => "unknown" }
    }
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "api-jmv-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }

}